Remove all non-Brave blessed extensions
brave/extension-whitelist pull request #64
Opened 2022-09-07 21:45 UTC by pes10k

This is part of a larger project to remove this (extension-whitelist) dependency all together

2022-09-07 22:29 UTC, fmarier requested changes

2022-09-07 22:29 UTC, fmarier commented on data/whitelist.json
> -            "description": "Web Store"
That one is not an extension (https://chrome.google.com/webstore/detail/line-share/ahfgeienlihckogmohjhadlkjgocpleb). I'm not sure what it is, but we should probably leave it in until we can identify it.

2022-09-07 22:30 UTC, fmarier commented
https://github.com/brave/brave-browser/wiki/Extension-whitelisting-process will need to be updated once this is merged.

2022-09-07 22:37 UTC, pes10k commented on data/whitelist.json
> -            "description": "Web Store"
sounds good, done and done

2022-09-07 23:38 UTC, fmarier requested changes
Two more we should keep. I think all of the other ones are regular third-party extensions.

2022-09-07 23:38 UTC, fmarier commented on data/whitelist.json
> -            "id": "mfehgcgbbipciphmccgaenjidiccnmng",
That's also not a real extension: https://chrome.google.com/webstore/detail/line-share/mfehgcgbbipciphmccgaenjidiccnmng

Probably some kind of Chromium component that gets installed automatically under some circumstances.

2022-09-07 23:38 UTC, fmarier commented on data/whitelist.json
> -            "description": "CryptoTokenExtension"
That's probably some kind of Brave thing. Also not on the extension store.

2022-09-08 07:27 UTC, bsclifton commented on data/whitelist.json
> -            "description": "CryptoTokenExtension"
I think this is something we used in Muon to have U2F support

2022-09-08 13:11 UTC, pes10k commented on data/whitelist.json
> -            "id": "mfehgcgbbipciphmccgaenjidiccnmng",
okay ive added this back in

2022-09-08 13:12 UTC, pes10k commented on data/whitelist.json
> -            "description": "CryptoTokenExtension"
Sounds good i'll keep it deleted

2022-09-08 18:03 UTC, fmarier approved these changes

2022-09-08 19:16 UTC, merged